In [8]:
#np加载文件 
import numpy as np

# 文件路径  文件内容分割  文件内容类型
src= np.genfromtxt("test.txt",delimiter=",",dtype=str)

print(src)
print(type(src))
#print (help(np.genfromtxt))

#创建数组
vector = np.array([1,2,3,4])
#创建矩阵
mat = np.array([[1,2,3],[2,3,4],[3,4,5]])
print(vector)
print(mat)

#打印mat的结构（此处 3 * 3 ）
print(mat.shape)


[['1111' 'hell1']
 ['1111' 'hell2']
 ['1111' 'hell3']
 ['1111' 'hell4']
 ['1111' 'hell5']
 ['1111' 'hell6']
 ['22222' 'hel7o']
 ['22222' 'hell8']
 ['22222' 'hell9']
 ['222' 'hell10']]
<class 'numpy.ndarray'>
[1 2 3 4]
[[1 2 3]
 [2 3 4]
 [3 4 5]]
(3, 3)


In [43]:
import numpy as np
#1.np.array([2,3,4,5])  里面的元素类型需要一致，如果不一致系统会自动转换
n = np.array([2,3,5.0])
#print(n)
#print(n.dtype)

#取矩阵中的数据，
#mat[i,j],取得i行，j列的数据
#mat[:,j]，取矩阵中的所有行 + 某列，切片操作（切片范围： 前闭后开）


vector = np.array([1,2,3,4])

vector == 2 # 相当于对array中每一个元素都进行了判断,输出array([False, True, False, False], dtype=bool)

mat = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5]
    ])

re = mat == 5 #矩阵也是同理,返回的re也是矩阵
             # array([[False, False, False],
             #       [False, False, False],
             #       False, False,  True]], dtype=bool)
print(re)
        
line = (mat[:,2] == 5) #在第三列数据中是否有元素等于5
print(line)

print(mat[:,line]) # 打印包含5的这一列
print(mat[line,:]) #打印包含5的这一行


#转换array里面的元素类型  str->float
v = np.array(["1","2","3"])
print(v.dtype)

v = v.astype(np.float32)
print(v.dtype)
print(v)



vc = np.array([1,2,3,4])
print(vc.min())
print(vc.max())


va = np.array([[5,10,15],
               [1,12,16],
               [2,10,15],
              ])
print(va.sum(axis = 1))#按行求和，[30 29 27]
print(va.sum(axis = 0))#按列求和，[ 8 32 46]









[[False False False]
 [False False False]
 [False False  True]]
[False False  True]
[[3]
 [4]
 [5]]
[[3 4 5]]
<U1
float32
[ 1.  2.  3.]
1
4
[30 29 27]
[ 8 32 46]


In [5]:
import cv2
import numpy as np

#将数组转化为矩阵
arr = np.array(np.arange(15))
print(arr)
mat35 =arr.reshape(3,5)
print(mat35)


#初始化一个元素全部为0的矩阵
mat_zero = np.zeros((3,4))
print(mat_zero)

#初始化一个元素全部为1的矩阵
mat_one = np.ones((3,4),dtype = np.int32)
print(mat_one)

#等间距数组，每隔多少一加
arrr = np.arange(10,30,5)
print(arrr) #[10 15 20 25]


#随机矩阵产生 （2 x 3） ，元素都小于1的矩阵
#[[ 0.95057742  0.3138582   0.5870517 ]
# [ 0.94591674  0.8639504   0.58936778]]
print(np.random.random((2,3)))

#0 到 100之间，平均去100个数
line = np.linspace(0,100,100)
print(line)












[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[10 15 20 25]
[[ 0.027599    0.90284663  0.76105206]
 [ 0.11708431  0.12932464  0.26755901]]
[   0.            1.01010101    2.02020202    3.03030303    4.04040404
    5.05050505    6.06060606    7.07070707    8.08080808    9.09090909
   10.1010101    11.11111111   12.12121212   13.13131313   14.14141414
   15.15151515   16.16161616   17.17171717   18.18181818   19.19191919
   20.2020202    21.21212121   22.22222222   23.23232323   24.24242424
   25.25252525   26.26262626   27.27272727   28.28282828   29.29292929
   30.3030303    31.31313131   32.32323232   33.33333333   34.34343434
   35.35353535   36.36363636   37.37373737   38.38383838   39.39393939
   40.4040404    41.41414141   42.42424242   43.43434343   44.44444444
   45.45454545   46.46464646   47.47474747   48.48484848   49.49494949
   

In [17]:
#nump 运算
import cv2
import numpy as np

arr1 = np.array([10,20,30])
arr2 = np.array([1,2,3])



#两个array 对应位置相减 
print("array - array:",arr1 - arr2) #[ 9 18 27]

arr3 = np.array([[10,20],[30,40]])
arr4 = np.array([[1,2],[3,4]])
print("矩阵减去矩阵：",arr3  * arr4) # 矩阵也是对应位置相加减乘除

arr4 = np.array([0,1,2,3,])
print("对array中的每个数据求平方：",arr4**2)#对array中的元素求平方 2为平方 3为立方 以此类推

print("大小判断：",arr4 < 2) #对array中的每个数据都进行比较



array - array: [ 9 18 27]
矩阵减去矩阵： [[ 10  40]
 [ 90 160]]
对array中的每个数据求平方： [0 1 4 9]
大小判断： [ True  True False False]


In [61]:
#矩阵操作
import cv2
import numpy as np

mat1 = np.array([[1,2],
                 [3,5]
                ])
mat2 = np.array([[2,4],
                 [1,2]
                ])

print("对应位置相乘：\n",mat1 * mat2)

print("矩阵标准乘法1：\n",mat1.dot(mat2))
print("矩阵标准乘法2：\n",np.dot(mat1,mat2))

print("随机获取 0到1之间的 3 x 4的矩阵：\n",np.random.random((3,4))) 
print("随机获取 0到10之间的 3 x 4的矩阵,向下取整：\n",np.floor(10*np.random.random((3,4))))

print("把矩阵变成数组：\n",mat1.flatten()) 

a = mat1.flatten()
a.shape = (2,2)#改变array的shape即可将array变成mat
a.shape = (2,-1) #列写为-1，系统自动根据数组的行数来计算出列，此处和a.shape = (2,2)等价
print("把数组变成矩阵：\n",a) 

print("求矩阵的转置：\n",mat1.T)



#矩阵拼接------------------------------------

a = np.random.random((2,2))
b = np.random.random((2,2))

print("origin a : \n",a)
print("origin b : \n",b)
print("横着拼接矩阵：\n",np.hstack((a,b)))
print("竖着拼接矩阵：\n",np.vstack((a,b)))

#矩阵切分------------------------------------

c = np.random.random((2,6))
print("origin c : \n",c)
print("切横方向矩阵，平均切：\n",np.hsplit(c,3))#变成三个 2 * 2的矩阵
print("切横方向矩阵，任意切：\n",np.hsplit(c,(1,2)))#切第一列，切第二列
#切竖方向 同理即可







对应位置相乘：
 [[ 2  8]
 [ 3 10]]
矩阵标准乘法1：
 [[ 4  8]
 [11 22]]
矩阵标准乘法2：
 [[ 4  8]
 [11 22]]
随机获取 0到1之间的 3 x 4的矩阵：
 [[ 0.53737047  0.3592954   0.12062045  0.26162941]
 [ 0.62167578  0.15119026  0.81601824  0.31363537]
 [ 0.86012452  0.12512046  0.49401051  0.03339177]]
随机获取 0到10之间的 3 x 4的矩阵,向下取整：
 [[ 6.  0.  7.  4.]
 [ 4.  8.  7.  8.]
 [ 3.  5.  9.  8.]]
把矩阵变成数组：
 [1 2 3 5]
把数组变成矩阵：
 [[1 2]
 [3 5]]
求矩阵的转置：
 [[1 3]
 [2 5]]
origin a : 
 [[ 0.26721609  0.15812952]
 [ 0.42758673  0.30698572]]
origin b : 
 [[ 0.25767492  0.28879398]
 [ 0.62202104  0.96387954]]
横着拼接矩阵：
 [[ 0.26721609  0.15812952  0.25767492  0.28879398]
 [ 0.42758673  0.30698572  0.62202104  0.96387954]]
竖着拼接矩阵：
 [[ 0.26721609  0.15812952]
 [ 0.42758673  0.30698572]
 [ 0.25767492  0.28879398]
 [ 0.62202104  0.96387954]]
origin c : 
 [[ 0.60119444  0.91982893  0.32659764  0.32176592  0.71956229  0.60762771]
 [ 0.76098384  0.67172499  0.11735097  0.80322314  0.95778647  0.28922526]]
切横方向矩阵，平均切：
 [array([[ 0.60119444,  0.91982893],
  

In [33]:

import numpy as np

arr = np.arange(4)
print("origin array:\n",arr)
print("e的0,1,2,3次幂:\n",np.exp(arr)) # e的0,1,2,3次幂
print("对 0,1,2,3,4开根号:\n",np.sqrt(arr))#对 0,1,2,3,4开根号


origin array:
 [0 1 2 3]
e的0,1,2,3次幂:
 [  1.           2.71828183   7.3890561   20.08553692]
对 0,1,2,3,4开根号:
 [ 0.          1.          1.41421356  1.73205081]


In [71]:
#复制操作

import numpy as np

a = np.arange(12)
b = a  #a b 指向同一块内存

print(a is b)
print(id(a))
print(id(b))

#改变a的属性
a.shape = (3,4)

#b的属性也跟着变了
print(b.shape)

print(a is b)
print(id(a))
print(id(b))

d = np.arange(12)
c = d.view()
print(c is d)
print(id(d))
print(id(c))

c[0] = 10
print(c)
print(d) # 此时 c[0] = 10 ,d[0] = 10,因此可以理解为 c d的容器地址不一样，但是数据使用的是同一数据


#深拷贝, f e没任何关系 -------------------------------------------------
f = np.arange(12)
e = f.copy()
print(e is f)




True
2260365872784
2260365872784
(3, 4)
True
2260365872784
2260365872784
False
2260365872704
2260365873024
[10  1  2  3  4  5  6  7  8  9 10 11]
[10  1  2  3  4  5  6  7  8  9 10 11]
False


In [84]:
#排序 索引
import numpy as np

arr = np.sin(np.arange(12)).reshape(3,4)
print("origin data :\n",arr)

arrV = arr.argmax(axis = 0)
print("找到每列中的最大值的索引:\n",arrV)

arrH = arr.argmax(axis = 1)
print("找到每行中的最大值的索引:\n",arrH)

print("通过每列最大值索引，找到每列最大值:\n",arr[arrV,range(arr.shape[1])])


origin data :
 [[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]]
找到每列中的最大值的索引:
 [2 0 0 1]
找到每行中的最大值的索引:
 [2 3 0]
通过每列最大值索引，找到最大值:
 [ 0.98935825  0.84147098  0.90929743  0.6569866 ]


In [87]:
#扩展
import numpy as np

arr = np.arange(0,40,10)
print(arr)

#把数组扩展成 2x2的矩阵
b = np.tile(arr,(2,2))
print(b)

[ 0 10 20 30]
[[ 0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30]]


In [105]:
#排序

import numpy as np

arr = np.array([[4,3,5],[1,2,1]])

print("每列排序 ：\n",np.sort(arr,axis =0))
print("每行排序 ：\n",np.sort(arr,axis =1))

print("行排序的索引：\n",np.argsort(arr,axis=1)) 
print("列排序的索引：\n",np.argsort(arr,axis=0)) 

每列排序 ：
 [[1 2 1]
 [4 3 5]]
每行排序 ：
 [[3 4 5]
 [1 1 2]]
行排序的索引：
 [[1 0 2]
 [0 2 1]]
列排序的索引：
 [[1 1 1]
 [0 0 0]]
