In [8]:
#np加载文件
import numpy as np

# 文件路径  文件内容分割  文件内容类型
src= np.genfromtxt("test.txt",delimiter=",",dtype=str)

print(src)
print(type(src))
#print (help(np.genfromtxt))

#创建数组
vector = np.array([1,2,3,4])
#创建矩阵
mat = np.array([[1,2,3],[2,3,4],[3,4,5]])
print(vector)
print(mat)

#打印mat的结构（此处 3 * 3 ）
print(mat.shape)


[['1111' 'hell1']
 ['1111' 'hell2']
 ['1111' 'hell3']
 ['1111' 'hell4']
 ['1111' 'hell5']
 ['1111' 'hell6']
 ['22222' 'hel7o']
 ['22222' 'hell8']
 ['22222' 'hell9']
 ['222' 'hell10']]
<class 'numpy.ndarray'>
[1 2 3 4]
[[1 2 3]
 [2 3 4]
 [3 4 5]]
(3, 3)


In [43]:
import numpy as np
#1.np.array([2,3,4,5])  里面的元素类型需要一致，如果不一致系统会自动转换
n = np.array([2,3,5.0])
#print(n)
#print(n.dtype)

#取矩阵中的数据，
#mat[i,j],取得i行，j列的数据
#mat[:,j]，取矩阵中的所有行 + 某列，切片操作（切片范围： 前闭后开）


vector = np.array([1,2,3,4])

vector == 2 # 相当于对array中每一个元素都进行了判断,输出array([False, True, False, False], dtype=bool)

mat = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5]
    ])

re = mat == 5 #矩阵也是同理,返回的re也是矩阵
             # array([[False, False, False],
             #       [False, False, False],
             #       False, False,  True]], dtype=bool)
print(re)
        
line = (mat[:,2] == 5) #在第三列数据中是否有元素等于5
print(line)

print(mat[:,line]) # 打印包含5的这一列
print(mat[line,:]) #打印包含5的这一行


#转换array里面的元素类型  str->float
v = np.array(["1","2","3"])
print(v.dtype)

v = v.astype(np.float32)
print(v.dtype)
print(v)



vc = np.array([1,2,3,4])
print(vc.min())
print(vc.max())


va = np.array([[5,10,15],
               [1,12,16],
               [2,10,15],
              ])
print(va.sum(axis = 1))#按行求和，[30 29 27]
print(va.sum(axis = 0))#按列求和，[ 8 32 46]









[[False False False]
 [False False False]
 [False False  True]]
[False False  True]
[[3]
 [4]
 [5]]
[[3 4 5]]
<U1
float32
[ 1.  2.  3.]
1
4
[30 29 27]
[ 8 32 46]


In [12]:
import cv2
import numpy as np

#将数组转化为矩阵
arr = np.array(np.arange(15))
print(arr)
mat35 =arr.reshape(3,5)
print(mat35)


#初始化一个元素全部为0的矩阵
mat_zero = np.zeros((3,4))
print(mat_zero)

#初始化一个元素全部为1的矩阵
mat_one = np.ones((3,4),dtype = np.int32)
print(mat_one)

#等间距数组，每隔多少一加
arrr = np.arange(10,30,5)
print(arrr) #[10 15 20 25]


#随机矩阵产生 （2 x 3） ，元素都小于1的矩阵
#[[ 0.95057742  0.3138582   0.5870517 ]
# [ 0.94591674  0.8639504   0.58936778]]
print(np.random.random((2,3)))








[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[10 15 20 25]
[[ 0.95057742  0.3138582   0.5870517 ]
 [ 0.94591674  0.8639504   0.58936778]]
